name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    outputs:
      syntax_ok: ${{ steps.python_lint.outcome == 'success' && steps.ruby_lint.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint black isort mypy
      
      - name: Check Python syntax and style
        id: python_lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pylint --disable=all --enable=syntax-error,undefined-variable,unused-import,unused-variable *.py
          black --check .
          isort --check .
          mypy --ignore-missing-imports .
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      
      - name: Install Ruby linting tools
        run: |
          gem install rubocop
      
      - name: Check Ruby syntax and style
        id: ruby_lint
        run: |
          rubocop homebrew/*.rb --only Syntax,Lint
  
  test:
    needs: syntax-check
    if: needs.syntax-check.outputs.syntax_ok == 'true'
    runs-on: macos-latest
    outputs:
      tests_passed: ${{ steps.run_tests.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tnefparse chardet beautifulsoup4
          brew install mpack
      
      - name: Run test suite
        id: run_tests
        run: |
          chmod +x test/run_tests.sh
          ./test/run_tests.sh