name: Update Homebrew Tap

# This workflow requires a repository secret named HOMEBREW_TAP_TOKEN
# Go to Settings > Secrets and variables > Actions > New repository secret
# Name it HOMEBREW_TAP_TOKEN and use a personal access token with repo scope
# The token needs write access to the homebrew-winmail repository

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to use (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-winmail repository
        uses: actions/checkout@v3
        with:
          repository: jsbattig/homebrew-winmail
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-winmail
      
      - name: Set up environment variables
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
            TAG_INPUT="${{ github.event.inputs.tag_name }}"
            echo "VERSION=${TAG_INPUT#v}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            echo "VERSION=${github.event.release.tag_name#v}" >> $GITHUB_ENV
          fi
      
      - name: Download release tarball and calculate checksum
        run: |
          curl -L https://github.com/jsbattig/py-winmail-opener/archive/refs/tags/${{ env.TAG_NAME }}.tar.gz -o release.tar.gz
          echo "SHA256=$(shasum -a 256 release.tar.gz | awk '{print $1}')" >> $GITHUB_ENV
      
      - name: Update formula
        run: |
          cd homebrew-winmail
          sed -i "s|url \".*\"|url \"https://github.com/jsbattig/py-winmail-opener/archive/refs/tags/${{ env.TAG_NAME }}.tar.gz\"|" py-winmail-opener.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ env.SHA256 }}\"|" py-winmail-opener.rb
          sed -i "s|\"winmail_opener .*\"|\"winmail_opener ${{ env.VERSION }}\"|" py-winmail-opener.rb
      
      - name: Commit and push changes
        run: |
          cd homebrew-winmail
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add py-winmail-opener.rb
          git commit -m "Update formula for py-winmail-opener ${{ env.TAG_NAME }}"
          git push
